###busca todas ferramentas

GET http://localhost:3001/tools
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJWVVRUUiIsInN1YiI6IjVlNGY3NmI2Njk1ZjUzNDIwODQ5NDNiNyIsImlhdCI6MTU4MjI2NjA0MH0.u3TxgrW66LHK9ewytqd5a0nIKbpGyLv68-JZ5Ts6DHk

### busca ferramentas pela query global

GET http://localhost:3001/tools
    ?global=
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJWVVRUUiIsInN1YiI6IjVlNGY3NmI2Njk1ZjUzNDIwODQ5NDNiNyIsImlhdCI6MTU4MjI2NjA0MH0.u3TxgrW66LHK9ewytqd5a0nIKbpGyLv68-JZ5Ts6DHk

### busca ferramentas pela query tag

GET http://localhost:3000/tools
    ?tag=Node

### add ferramenta

POST http://localhost:3001/tools
content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJWVVRUUiIsInN1YiI6IjVlNGY3NmI2Njk1ZjUzNDIwODQ5NDNiNyIsImlhdCI6MTU4MjI2NjA0MH0.u3TxgrW66LHK9ewytqd5a0nIKbpGyLv68-JZ5Ts6DHk


{
    "title": "Figura",
    "link": "https://github.com/typicode/hotel",
    "description": "Local app manager. Start apps within your browser, developer tool with local .localhost domain and https out of the box.",
    "tags": [
        "node",
        "organizing",
        "webapps",
        "domain",
        "developer",
        "https",
        "proxy"
    ]
}

### remove ferramenta

DELETE http://localhost:3000/tools/5e4f5405e1bed453509ad434





### post user

POST http://localhost:3001/user/cadastrar
content-type: application/json

{
    "firstName": "jarn401",
    "lastName": "Neto",
    "login": "jarn4012",
    "password": "123",
    "avatar": "https://avatars1.githubusercontent.com/u/20113585?s=460&v=4"
}

### Logar
POST http://3.16.40.249:3001/user/logar
content-type: application/json

{
    "login": "jarn40",
    "password": "123"
}


### deletar usuario
DELETE http://localhost:3001/user/5e56a7c91575415d407ee4b6
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJWVVRUUiIsInN1YiI6IjVlNGY3NmI2Njk1ZjUzNDIwODQ5NDNiNyIsImlhdCI6MTU4MjI2NjA0MH0.u3TxgrW66LHK9ewytqd5a0nIKbpGyLv68-JZ5Ts6DHk

### buscar usuario
GET http://localhost:3001/user/5e56a7c91575415d407ee4b6
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJWVVRUUiIsInN1YiI6IjVlNTZhN2M5MTU3NTQxNWQ0MDdlZTRiNiIsImlhdCI6MTU4Mjg1OTg4MH0.HYfEl18jJFA3V3jE5XJkRxHrpj-qK-GjaWu5lhUzePw